2017-06-18 19:40:46,094 - root - INFO - Logger setup done, starting web server
2017-06-18 19:40:46,095 - CANServer - INFO - Logger Added
2017-06-18 19:41:26,456 - root - INFO - Logger setup done, starting web server
2017-06-18 19:41:26,457 - CANServer - INFO - Logger Added
2017-06-18 19:41:53,962 - root - INFO - Logger setup done, starting web server
2017-06-18 19:41:53,963 - CANServer - INFO - Logger Added
2017-06-18 19:44:52,506 - root - INFO - Logger setup done, starting web server
2017-06-18 19:44:52,507 - CANServer - INFO - Logger Added
2017-06-18 19:45:41,125 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:45:41,130 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:45:51,371 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:45:51,375 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:47:18,476 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:47:18,481 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:47:34,298 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=KeyError('updateRate',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 129, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 110, in consumer
    co["toMin"], co["updateRate"], co["toMax"],
KeyError: 'updateRate'
2017-06-18 19:49:09,902 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:49:09,906 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 128, in consumer_handler
    message = await websocket.recv()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
2017-06-18 19:49:11,832 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=TypeError("'<' not supported between instances of 'str' and 'int'",)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 129, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 116, in consumer
    if co["updateRate"] < self.updateRate:
TypeError: '<' not supported between instances of 'str' and 'int'
2017-06-18 19:51:50,297 - root - INFO - Logger setup done, starting web server
2017-06-18 19:51:50,298 - CANServer - INFO - Logger Added
2017-06-18 19:51:54,637 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=Exception('SocketCAN not available under win32',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 129, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 119, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 36, in initNetwork
    network.connect(channel='can0', bustype='socketcan', bitrate=125000)
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\canopen\network.py", line 92, in connect
    self.bus = can.interface.Bus(*args, **kwargs)
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\can\interfaces\interface.py", line 31, in __new__
    can.rc['interface'] = choose_socketcan_implementation()
  File "C:\Users\Tinus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\can\util.py", line 130, in choose_socketcan_implementation
    raise Exception(msg)
Exception: SocketCAN not available under win32
2017-06-18 19:59:25,642 - root - INFO - Logger setup done, starting web server
2017-06-18 19:59:25,643 - CANServer - INFO - Logger Added
2017-06-18 19:59:31,589 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 129, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 119, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 87, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 87, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 87, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  [Previous line repeated 970 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:01:43,962 - root - INFO - Logger setup done, starting web server
2017-06-18 20:01:43,962 - CANServer - INFO - Logger Added
2017-06-18 20:01:50,601 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:127> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 130, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 120, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  [Previous line repeated 970 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:02:05,264 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:127> exception=RecursionError('maximum recursion depth exceeded in comparison',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 130, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 120, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  [Previous line repeated 974 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 561, in probe_stack
    if depth == 0:
RecursionError: maximum recursion depth exceeded in comparison
2017-06-18 20:04:01,184 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:127> exception=RecursionError('maximum recursion depth exceeded in comparison',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 130, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 120, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(co.updateRate, self.sdo_update(co)).start()
  [Previous line repeated 974 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 561, in probe_stack
    if depth == 0:
RecursionError: maximum recursion depth exceeded in comparison
2017-06-18 20:05:43,473 - root - INFO - Logger setup done, starting web server
2017-06-18 20:05:43,473 - CANServer - INFO - Logger Added
2017-06-18 20:05:51,267 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:127> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 130, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 120, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 970 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:07:11,963 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:127> exception=RecursionError('maximum recursion depth exceeded in comparison',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 130, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 120, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 974 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 561, in probe_stack
    if depth == 0:
RecursionError: maximum recursion depth exceeded in comparison
2017-06-18 20:08:22,382 - root - INFO - Logger setup done, starting web server
2017-06-18 20:08:22,382 - CANServer - INFO - Logger Added
2017-06-18 20:08:28,576 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:128> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 131, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 121, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 89, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 89, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 89, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 970 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:10:44,911 - root - INFO - Logger setup done, starting web server
2017-06-18 20:10:44,911 - CANServer - INFO - Logger Added
2017-06-18 20:10:51,983 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 129, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 119, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 970 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:12:34,388 - root - INFO - Logger setup done, starting web server
2017-06-18 20:12:34,390 - CANServer - INFO - Logger Added
2017-06-18 20:12:59,100 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 129, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 119, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 970 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:14:02,602 - root - INFO - Logger setup done, starting web server
2017-06-18 20:14:02,603 - CANServer - INFO - Logger Added
2017-06-18 20:14:28,063 - root - INFO - Logger setup done, starting web server
2017-06-18 20:14:28,064 - CANServer - INFO - Logger Added
2017-06-18 20:14:54,125 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:126> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 129, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 119, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 54, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 88, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 970 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 83, in sdo_update
    self.CAN_Data[co.key] = co.getData(self.node)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANObject.py", line 32, in getData
    print('mode', self.mode)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:40:58,280 - root - INFO - Logger setup done, starting web server
2017-06-18 20:40:58,281 - CANServer - INFO - Logger Added
2017-06-18 20:41:04,803 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:129> exception=RecursionError('maximum recursion depth exceeded',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 132, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 122, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 56, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 91, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 91, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 91, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 971 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 85, in sdo_update
    print("Set update for:", co.key)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 558, in probe_stack
    def probe_stack(depth = 10):
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 971, in trace_func
    return self._events[event](frame, arg)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 977, in handle_call
    self.push_frame(frame)
RecursionError: maximum recursion depth exceeded
2017-06-18 20:55:02,569 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<CANServer.consumer_handler() done, defined at c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py:129> exception=RecursionError('maximum recursion depth exceeded in comparison',)>
Traceback (most recent call last):
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 132, in consumer_handler
    await self.consumer(message)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 122, in consumer
    self.initNetwork()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 56, in initNetwork
    self.sdo_update(co)
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 91, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 91, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 91, in sdo_update
    threading.Timer(float(co.updateRate), self.sdo_update(co)).start()
  [Previous line repeated 975 more times]
  File "c:\Users\Tinus\Documents\Projects\e-Kart\CAN bus\CANServer\CANServer\python\CANServer.py", line 85, in sdo_update
    print("Set update for:", co.key)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 2512, in write
    probe_stack(3)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 563, in probe_stack
    probe_stack(depth - 1)
  File "C:\Users\Tinus\.vscode\extensions\donjayamanne.python-0.6.5\pythonFiles\PythonTools\visualstudio_py_debugger.py", line 561, in probe_stack
    if depth == 0:
RecursionError: maximum recursion depth exceeded in comparison
2017-06-18 21:03:58,681 - root - INFO - Logger setup done, starting web server
2017-06-18 21:03:58,682 - CANServer - INFO - Logger Added
2017-06-18 21:05:55,810 - root - INFO - Logger setup done, starting web server
2017-06-18 21:05:55,811 - CANServer - INFO - Logger Added
2017-06-18 21:15:25,841 - root - INFO - Logger setup done, starting web server
2017-06-18 21:15:25,842 - CANServer - INFO - Logger Added
2017-06-18 21:16:00,795 - root - INFO - Logger setup done, starting web server
2017-06-18 21:16:00,795 - CANServer - INFO - Logger Added
2017-06-18 21:16:55,126 - root - INFO - Logger setup done, starting web server
2017-06-18 21:16:55,127 - CANServer - INFO - Logger Added
